# Generated by Django 3.1.2 on 2020-10-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpredict', '0008_auto_20201018_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskclassification',
            name='deadline',
            field=models.DateTimeField(verbose_name='〆切日時'),
        ),
    ]
